version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: phoenix_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "phoenix_rss"
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: phoenix_redis
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgresql_data:
