version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: phoenix_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "phoenix_rss"
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: phoenix_redis
    ports:
      - "127.0.0.1:6379:6379"

  kafka:
    image: bitnami/kafka:3.7
    container_name: phoenix_kafka
    ports:
      - "127.0.0.1:19092:19092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:29093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:29093,CLIENT://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CLIENT://localhost:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1

volumes:
  postgresql_data:
